version: '3.8'

services:
  app:
    build: .
    container_name: forum-app
    ports:
      - "3000:3000"  
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    volumes:
      - .:/usr/src/app



